### ISSUE TITLE
error: argument --num-thread-pipeline: invalid int value: '${NTH_PIPELINE}'

### ISSUE THREAD

**Issue by jisraeli** [kundajelab/ENCODE_downloader#1]
I tried the encode downloader example by running `python2 ENCODE_downloader.py /srv/scratch/jisraeli/encode3_chipseq/ ENCODE3 DNA+accessibility ATAC-seq Homo+sapiens hg38_ENCODE` on `surya` and got `ENCODE fastq downloader: error: argument --num-thread-pipeline: invalid int value: '${NTH_PIPELINE}'`

**Comment by leepc12** [comment]
fixed
