### ISSUE TITLE
example command gives TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by jisraeli** [kundajelab/ENCODE_downloader#2]
I tried running `python2 ENCODE_downloader.py /srv/scratch/jisraeli/encode3_chipseq/ ENCODE3 DNA+accessibility ATAC-seq Homo+sapiens --ignored-accession-ids-file ignored_accession_ids.txt` and got

```
Traceback (most recent call last):
  File "ENCODE_downloader.py", line 176, in <module>
    args.ref_genome, param_pipeline)
TypeError: %d format: a number is required, not str
```

Am I running this correctly?

**Comment by leepc12** [comment]
fixed in the commit 39845872b1734fea953499799047f38c90aecf37
