### ISSUE TITLE
line 186

### ISSUE THREAD

**Issue by brianpenghe** [kundajelab/ENCODE_downloader#3]
Hi Anshul lab,
I tried your script with no options specified but got an error. The same error occurred when I ran your example command. Any ideas of that? 

Thanks.

Brian$ python3 ENCODE_downloader.py  
  File "ENCODE_downloader.py", line 186
    print '# of downloads exceeded the limit (%d), retrying in 20 seconds...' % (args.max_download,)
                                                                            ^
SyntaxError: invalid syntax

**Comment by leepc12** [comment]
I updated the code to take in search query URL in command line argument.
Please see an example on README.
